-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 20:14:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ReservaHotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ReservaHotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ReservaHotel` DEFAULT CHARACTER SET utf8 ;
USE `ReservaHotel` ;

-- -----------------------------------------------------
-- Table `ReservaHotel`.`Habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReservaHotel`.`Habitaciones` (
  `Habitacionescol` VARCHAR(45) NOT NULL,
  `tipo_habitacion` TEXT NOT NULL,
  `capacidad` INT NOT NULL,
  `precio_por_noche` FLOAT NOT NULL,
  `numero_habitacion` INT NOT NULL,
  UNIQUE INDEX `numero_habitacion_UNIQUE` (`numero_habitacion` ASC) VISIBLE,
  PRIMARY KEY (`Habitacionescol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReservaHotel`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReservaHotel`.`Clientes` (
  `id_Cliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `correo_electronico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReservaHotel`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReservaHotel`.`Reservas` (
  `id_Reserva` INT NOT NULL AUTO_INCREMENT,
  `id_Cliente` INT NOT NULL,
  `numero_habitacion` INT NOT NULL,
  `fecha_llegada` TIME NOT NULL,
  `fecha_salida` TIME NOT NULL,
  PRIMARY KEY (`id_Reserva`),
  UNIQUE INDEX `id_Cliente_UNIQUE` (`id_Cliente` ASC) VISIBLE,
  UNIQUE INDEX `id_Reserva_UNIQUE` (`id_Reserva` ASC) VISIBLE,
  INDEX `numero_habitacion_idx` (`numero_habitacion` ASC) VISIBLE,
  CONSTRAINT `id_Cliente`
    FOREIGN KEY (`id_Cliente`)
    REFERENCES `ReservaHotel`.`Clientes` (`id_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `numero_habitacion`
    FOREIGN KEY (`numero_habitacion`)
    REFERENCES `ReservaHotel`.`Habitaciones` (`numero_habitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
